### ISSUE TITLE
bert-base-uncased section requires AzureML not first search result

### ISSUE THREAD

**Issue by mihidumh** [MicrosoftLearning/advanced-gen-ai#2]
Description of issue

In the below steps, the first option that comes up when searching "bert-base-uncased" is from HuggingFace, but only the one from AzureML can be used for fine-tuning which is found by using the search filter "Curated by Azure AI".

Repro Steps:

- Navigate to the Model catalog, using the menu on the left.
- Search for and select the bert-base-uncased model.
- Select Finetune.

**Comment by Rndstad** [comment]
@mihidumh thank you for pointing this out, and I was not sharp since I was already thinking why don't I see the "finetune" button 🤕

**Comment by madiepev** [comment]
Thanks for reporting this. I'll add filtering for AzureML curated models to the steps.
